CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text,
	"email" varchar(320),
	"phone" varchar(32),
	"password_hash" text,
	"security_q" text,
	"security_a_hash" text,
	"avatar" text,
	"addresses" jsonb,
	"wishlist" jsonb,
	"cart" jsonb,
	"two_fa_enabled" boolean DEFAULT false,
	"role" text DEFAULT 'user',
	"referred_by" text,
	"created_at" text,
	"last_login_at" text,
	"points_balance" integer DEFAULT 0,
	"discount_percent" integer DEFAULT 0,
	"discount_reason" text,
	"referral_reward_count" integer DEFAULT 0,
	"permissions" jsonb,
	"recently_viewed" jsonb,
	"open_id" varchar(64),
	"login_method" varchar(64),
	"updated_at" text,
	CONSTRAINT "users_open_id_unique" UNIQUE("open_id")
);
